version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  service_a:
    build: ./service_a
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
    ports:
      - "8000:8000"
  service_b:
    build: ./service_b
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
    ports:
      - "8001:8000"